apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vxxc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vxxc
    app.kubernetes.io/part-of: tkwch-fix-0075-0005-app
  name: devfile-sample-vxxc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vxxc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vxxc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0005-tenant/tkwch-fix-0075-0005-app/devfile-sample-vxxc@sha256:0ef6594469800da01177c4e2fdd5b8a39a57fd26afdef9f042f775d294934c5b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
